remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional configuration variables
# title: "Your Site Title"
# description: "A brief description of your site"
show_downloads: false  # Set to true if you want download links
# google_analytics: "UA-XXXXX-Y"  # Uncomment and add your GA tracking ID
